ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_cost NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS estimated_profit NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS unit_cost NUMERIC(10,2) DEFAULT 0.00;
