ALTER TABLE orders ADD COLUMN total_cost NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN estimated_profit NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE order_items ADD COLUMN unit_cost NUMERIC(10,2) DEFAULT 0.00;
